export interface Design {
  active: string,
  background?: string,
  black: string,
  blockBackground?: string,
  blockTextColor?: string,
  buttonActiveBackground?: string,
  buttonActiveTextColor?: string,
  buttonBackground?: string,
  buttonReversedActiveBackground?: string,
  buttonReversedActiveTextColor?: string,
  buttonReversedBackground?: string,
  buttonReversedTextColor?: string,
  buttonTextColor?: string,
  ContentTextColor?: string,
  muted: string,
  mutedBackground?: string,
  mutedTextColor?: string,
  navBackground?: string,
  primary: string,
  secondary: string,
}
